version: '3.8'

services:
  django:
    image: django-33497
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn django_33497.asgi:application --host 0.0.0.0 --port 8000 --workers 3
    entrypoint: [ "/home/app/web/entrypoint.sh" ]
    volumes:
      - static_volume:/home/app/web/django_33497/static/
      - postgres_socket:/var/run/postgresql/
    depends_on:
      - postgres
      - nginx

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - static_volume:/home/app/web/django_33497/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

volumes:
  postgres_data:
  postgres_socket:
  static_volume:
